<?php
require_once '../includes/admin_auth.php';
$pdo->exec("CREATE TABLE IF NOT EXISTS agenda_estudos (id INT AUTO_INCREMENT PRIMARY KEY, usuario_id INT NOT NULL, titulo VARCHAR(120) NOT NULL, tema VARCHAR(100) NOT NULL, data_estudo DATE NOT NULL, hora_inicio TIME NOT NULL DEFAULT '16:00:00', duracao_minutos SMALLINT NOT NULL DEFAULT 30, observacoes VARCHAR(500) NULL, concluido TINYINT(1) NOT NULL DEFAULT 0, criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_agenda_usuario_data (usuario_id, data_estudo), CONSTRAINT fk_agenda_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$monthInput=(string)($_GET['m']??date('Y-m'));$month=DateTimeImmutable::createFromFormat('!Y-m-d',$monthInput.'-01');if(!$month||$month->format('Y-m')!==$monthInput)$month=new DateTimeImmutable(date('Y-m-01'));$start=$month->format('Y-m-01');$end=$month->modify('last day of this month')->format('Y-m-d');
$requested=(string)($_GET['date']??'');$selected=DateTimeImmutable::createFromFormat('!Y-m-d',$requested);if(!$selected||$selected->format('Y-m-d')!==$requested||$selected->format('Y-m')!==$month->format('Y-m'))$selected=$month->format('Y-m')===date('Y-m')?new DateTimeImmutable('today'):$month;$selectedKey=$selected->format('Y-m-d');
$stmt=$pdo->prepare("SELECT a.data_estudo,COUNT(*) total,SUM(a.concluido=1) concluidas FROM agenda_estudos a JOIN usuarios u ON u.id=a.usuario_id AND u.tipo='aluno' WHERE a.data_estudo BETWEEN ? AND ? GROUP BY a.data_estudo");$stmt->execute([$start,$end]);$counts=[];foreach($stmt->fetchAll() as $row)$counts[$row['data_estudo']]=$row;
$stmt=$pdo->prepare("SELECT a.titulo,a.tema,a.data_estudo,a.hora_inicio,a.duracao_minutos,a.concluido,u.nome aluno_nome FROM agenda_estudos a JOIN usuarios u ON u.id=a.usuario_id WHERE u.tipo='aluno' AND a.data_estudo=? ORDER BY a.hora_inicio,u.nome");$stmt->execute([$selectedKey]);$dayEvents=$stmt->fetchAll();$stmt=$pdo->prepare("SELECT COUNT(*) FROM agenda_estudos a JOIN usuarios u ON u.id=a.usuario_id WHERE u.tipo='aluno' AND a.data_estudo BETWEEN ? AND ?");$stmt->execute([$start,$end]);$total=(int)$stmt->fetchColumn();$studentCount=(int)$pdo->query("SELECT COUNT(*) FROM usuarios WHERE tipo='aluno'")->fetchColumn();
$weekday=(int)$month->format('N');$gridStart=$month->modify('-'.($weekday-1).' days');$gridDays=(int)ceil(($weekday-1+(int)$month->format('t'))/7)*7;$previous=$month->modify('-1 month');$next=$month->modify('+1 month');$monthNames=[1=>'janeiro',2=>'fevereiro',3=>'março',4=>'abril',5=>'maio',6=>'junho',7=>'julho',8=>'agosto',9=>'setembro',10=>'outubro',11=>'novembro',12=>'dezembro'];$weekdays=['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'];
?>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Agenda dos alunos | Química Study</title><link rel="stylesheet" href="../css/style.css?v=20261010-brand-agenda"><link rel="stylesheet" href="../css/dashboard.css?v=20261010-brand-agenda"><link rel="stylesheet" href="../css/teacher-agenda.css?v=20261010-brand-agenda"></head>
<body class="dashboard-body"><div class="app-container"><aside class="sidebar"><div class="sidebar-header"><a href="dashboard.php" class="logo brand-logo"><img src="../assets/logo-chem.svg" alt=""><span class="brand-name">Química<span>STUDY</span></span></a></div><nav class="sidebar-nav" aria-label="Navegação do professor"><a href="dashboard.php" class="nav-item"><span class="icon">▦</span> Painel</a><a href="usuarios.php" class="nav-item"><span class="icon">♙</span> Alunos</a><a href="conteudos.php" class="nav-item"><span class="icon">▤</span> Conteúdos</a><a href="questoes.php" class="nav-item"><span class="icon">?</span> Questões</a><a href="simulados.php" class="nav-item"><span class="icon">✎</span> Simulados</a><a href="resultados.php" class="nav-item"><span class="icon">↗</span> Resultados</a><a href="agenda.php" class="nav-item active" aria-current="page"><span class="icon">▦</span> Agenda dos alunos</a></nav><div class="sidebar-footer"><a href="../logout.php" class="nav-item logout"><span class="icon">↪</span> Sair</a></div></aside>
<main class="main-content"><header class="topbar"><div class="user-info"><span class="user-name">Área do professor</span></div></header><div class="content-wrapper teacher-agenda-page"><header class="teacher-agenda-hero"><div><span class="teacher-agenda-kicker">ACOMPANHAMENTO DA TURMA</span><h1>Agenda de estudos</h1><p>Veja quando os alunos planejam estudar e acompanhe a constância da turma.</p></div><span class="teacher-agenda-mark" aria-hidden="true">✦</span></header>
<section class="teacher-agenda-stats" aria-label="Resumo do mês"><article><span>Planos neste mês</span><strong><?= $total ?></strong></article><article><span>Alunos cadastrados</span><strong><?= $studentCount ?></strong></article><article><span>Dia selecionado</span><strong><?= count($dayEvents) ?></strong></article></section>
<div class="teacher-agenda-layout"><section class="teacher-calendar-card" aria-label="Calendário mensal"><header class="teacher-calendar-toolbar"><div><span class="teacher-agenda-kicker">CALENDÁRIO DA TURMA</span><h2><?= escape($monthNames[(int)$month->format('n')]) ?> <span><?= $month->format('Y') ?></span></h2></div><nav aria-label="Navegar meses"><a href="?m=<?= $previous->format('Y-m') ?>" aria-label="Mês anterior">‹</a><a class="teacher-today" href="?m=<?= date('Y-m') ?>&amp;date=<?= date('Y-m-d') ?>">Hoje</a><a href="?m=<?= $next->format('Y-m') ?>" aria-label="Próximo mês">›</a></nav></header><div class="teacher-calendar-grid teacher-weekdays"><?php foreach($weekdays as $day): ?><span><?= $day ?></span><?php endforeach; ?></div><div class="teacher-calendar-grid teacher-days"><?php for($i=0;$i<$gridDays;$i++):$day=$gridStart->modify('+'.$i.' days');$key=$day->format('Y-m-d');$info=$counts[$key]??null;$outside=$day->format('m')!==$month->format('m'); ?><a class="teacher-day <?= $outside?'is-outside':'' ?> <?= $key===date('Y-m-d')?'is-today':'' ?> <?= $key===$selectedKey?'is-selected':'' ?> <?= $info?'has-plans':'' ?>" href="?m=<?= $day->format('Y-m') ?>&amp;date=<?= $key ?>" aria-label="<?= $day->format('d/m/Y') ?>, <?= (int)($info['total']??0) ?> planos"><span><?= $day->format('j') ?></span><?php if($info): ?><small><?= (int)$info['total'] ?> <?= (int)$info['total']===1?'plano':'planos' ?></small><?php endif; ?></a><?php endfor; ?></div><footer class="teacher-calendar-legend"><span><i></i> Há sessões planejadas</span><span><b></b> Hoje</span></footer></section>
<aside class="teacher-day-panel"><header><div><span class="teacher-agenda-kicker">PLANOS DA TURMA</span><h2><?= $selected->format('d') ?> de <?= escape($monthNames[(int)$selected->format('n')]) ?></h2></div><strong><?= count($dayEvents) ?></strong></header><?php if($dayEvents): ?><div class="teacher-day-list"><?php foreach($dayEvents as $event): ?><article class="teacher-day-event"><span class="teacher-event-time"><?= substr($event['hora_inicio'],0,5) ?></span><div><strong><?= escape($event['titulo']) ?></strong><span><?= escape($event['tema']) ?> · <?= (int)$event['duracao_minutos'] ?> min</span><small>Aluno: <?= escape($event['aluno_nome']) ?></small></div><span class="teacher-event-status <?= (int)$event['concluido']?'is-done':'' ?>"><?= (int)$event['concluido']?'Concluída':'Planejada' ?></span></article><?php endforeach; ?></div><?php else: ?><div class="teacher-day-empty"><span>▦</span><strong>Nenhuma sessão planejada</strong><p>Escolha outra data no calendário para acompanhar os planos dos alunos.</p></div><?php endif; ?></aside></div><p class="teacher-agenda-note">Aqui você acompanha o planejamento de estudos da turma. As observações pessoais de cada aluno continuam privadas.</p></div></main></div><script src="../js/script.js?v=20261010-brand-agenda"></script></body></html>
