<?php
$titulo_pagina='Agenda de estudos'; $css_extra='agenda.css';
require_once '../includes/header.php';
$usuario_id=(int)$_SESSION['usuario_id'];
$pdo->exec("CREATE TABLE IF NOT EXISTS agenda_estudos (
 id INT AUTO_INCREMENT PRIMARY KEY,
 usuario_id INT NOT NULL,
 titulo VARCHAR(120) NOT NULL,
 tema VARCHAR(100) NOT NULL,
 data_estudo DATE NOT NULL,
 hora_inicio TIME NOT NULL DEFAULT '16:00:00',
 duracao_minutos SMALLINT NOT NULL DEFAULT 30,
 observacoes VARCHAR(500) NULL,
 concluido TINYINT(1) NOT NULL DEFAULT 0,
 criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 INDEX idx_agenda_usuario_data (usuario_id, data_estudo),
 CONSTRAINT fk_agenda_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$_SESSION['agenda_csrf']??=bin2hex(random_bytes(32));$error='';
$monthInput=(string)($_GET['m']??date('Y-m'));$month=DateTimeImmutable::createFromFormat('!Y-m-d',$monthInput.'-01');
if(!$month||$month->format('Y-m')!==$monthInput)$month=new DateTimeImmutable(date('Y-m-01'));
$monthStart=$month->format('Y-m-01');$monthEnd=$month->modify('last day of this month')->format('Y-m-d');
$requestedDate=(string)($_GET['date']??'');$selectedDate=DateTimeImmutable::createFromFormat('!Y-m-d',$requestedDate);
if(!$selectedDate||$selectedDate->format('Y-m-d')!==$requestedDate||$selectedDate->format('Y-m')!==$month->format('Y-m'))$selectedDate=$month->format('Y-m')===date('Y-m')?new DateTimeImmutable('today'):$month;
$selectedDateString=$selectedDate->format('Y-m-d');
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!is_string($_POST['csrf']??null)||!hash_equals($_SESSION['agenda_csrf'],$_POST['csrf'])){$error='A sessão expirou. Atualize a página e tente novamente.';}
 else{
  $action=(string)($_POST['action']??'');
  if($action==='add'){
   $title=trim((string)($_POST['titulo']??''));$topic=trim((string)($_POST['tema']??''));$date=(string)($_POST['data_estudo']??'');$time=(string)($_POST['hora_inicio']??'');$duration=filter_var($_POST['duracao']??30,FILTER_VALIDATE_INT);$notes=trim((string)($_POST['observacoes']??''));
   $validDate=DateTimeImmutable::createFromFormat('!Y-m-d',$date);
   if($title===''||mb_strlen($title)>120||$topic===''||mb_strlen($topic)>100||!$validDate||$validDate->format('Y-m-d')!==$date||!preg_match('/^(?:[01]\d|2[0-3]):[0-5]\d$/',$time)||!$duration||$duration<10||$duration>300||mb_strlen($notes)>500){$error='Confira os campos: atividade, tema, data, horário e duração entre 10 e 300 minutos.';}
   else{$stmt=$pdo->prepare('INSERT INTO agenda_estudos (usuario_id,titulo,tema,data_estudo,hora_inicio,duracao_minutos,observacoes) VALUES (:uid,:titulo,:tema,:data,:hora,:duracao,:obs)');$stmt->execute(['uid'=>$usuario_id,'titulo'=>$title,'tema'=>$topic,'data'=>$date,'hora'=>$time.':00','duracao'=>$duration,'obs'=>$notes===''?null:$notes]);$_SESSION['agenda_notice']='Sessão adicionada à sua agenda.';$_SESSION['agenda_csrf']=bin2hex(random_bytes(32));header('Location: agenda.php?m='.$validDate->format('Y-m').'&date='.$date.'#dia-selecionado');exit;}
  }elseif($action==='toggle'||$action==='delete'){
   $eventId=filter_var($_POST['event_id']??null,FILTER_VALIDATE_INT);
   if($eventId){if($action==='toggle'){$stmt=$pdo->prepare('UPDATE agenda_estudos SET concluido=1-concluido WHERE id=:id AND usuario_id=:uid');$stmt->execute(['id'=>$eventId,'uid'=>$usuario_id]);$_SESSION['agenda_notice']='Status da sessão atualizado.';}else{$stmt=$pdo->prepare('DELETE FROM agenda_estudos WHERE id=:id AND usuario_id=:uid');$stmt->execute(['id'=>$eventId,'uid'=>$usuario_id]);$_SESSION['agenda_notice']='Sessão removida da agenda.';}$back=(string)($_POST['data_estudo']??$selectedDateString);$backDate=DateTimeImmutable::createFromFormat('!Y-m-d',$back);if(!$backDate||$backDate->format('Y-m-d')!==$back)$backDate=$selectedDate;$_SESSION['agenda_csrf']=bin2hex(random_bytes(32));header('Location: agenda.php?m='.$backDate->format('Y-m').'&date='.$backDate->format('Y-m-d').'#dia-selecionado');exit;}
   $error='Não foi possível localizar essa sessão.';
  }else{$error='Ação inválida.';}
 }
}
$notice=$_SESSION['agenda_notice']??'';unset($_SESSION['agenda_notice']);
$stmt=$pdo->prepare('SELECT id,titulo,tema,data_estudo,hora_inicio,duracao_minutos,observacoes,concluido FROM agenda_estudos WHERE usuario_id=:uid AND data_estudo BETWEEN :inicio AND :fim ORDER BY data_estudo,hora_inicio,id');$stmt->execute(['uid'=>$usuario_id,'inicio'=>$monthStart,'fim'=>$monthEnd]);$events=$stmt->fetchAll();$byDay=[];foreach($events as $event)$byDay[$event['data_estudo']][]=$event;
$weekday=(int)$month->format('N');$gridStart=$month->modify('-'.($weekday-1).' days');$lastDay=(int)$month->format('t');$gridDays=(int)ceil(($weekday-1+$lastDay)/7)*7;$previous=$month->modify('-1 month');$next=$month->modify('+1 month');$doneCount=count(array_filter($events,static fn($e)=>(int)$e['concluido']===1));$openCount=count($events)-$doneCount;
$weekdays=['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'];$monthNames=[1=>'janeiro',2=>'fevereiro',3=>'março',4=>'abril',5=>'maio',6=>'junho',7=>'julho',8=>'agosto',9=>'setembro',10=>'outubro',11=>'novembro',12=>'dezembro'];$monthName=$monthNames[(int)$month->format('n')];$monthTitle=$monthName.' '.$month->format('Y');
?>
<section class="agenda-page">
 <header class="agenda-hero"><div><span class="panel-eyebrow">SEU RITMO, SEU PLANO</span><h1>Agenda de estudos</h1><p>Organize pequenas sessões de estudo e acompanhe sua constância, sem sobrecarregar a semana.</p></div><div class="agenda-hero-stat"><strong><?= count($events) ?></strong><span>sessões<br>neste mês</span></div></header>
 <?php if($notice): ?><div class="agenda-alert" role="status"><?= escape($notice) ?></div><?php endif; ?><?php if($error): ?><div class="agenda-alert agenda-error" role="alert"><?= escape($error) ?></div><?php endif; ?>
 <section class="agenda-summary"><article><span class="agenda-summary-icon">◷</span><div><strong><?= $openCount ?></strong><small>Para estudar</small></div></article><article><span class="agenda-summary-icon done">✓</span><div><strong><?= $doneCount ?></strong><small>Concluídas neste mês</small></div></article><article><span class="agenda-summary-icon accent">✦</span><div><strong><?= count($events) ?></strong><small>Sessões planejadas</small></div></article></section>
 <div class="agenda-layout"><section class="agenda-calendar-card" aria-label="Calendário mensal"><header class="calendar-toolbar"><div><span class="panel-eyebrow">CALENDÁRIO DE ESTUDOS</span><h2><span class="calendar-month-name"><?= escape($monthName) ?></span> <?= $month->format('Y') ?></h2></div><nav aria-label="Navegar meses"><a href="?m=<?= $previous->format('Y-m') ?>" aria-label="Mês anterior">‹</a><a class="calendar-today" href="?m=<?= date('Y-m') ?>&date=<?= date('Y-m-d') ?>">Hoje</a><a href="?m=<?= $next->format('Y-m') ?>" aria-label="Próximo mês">›</a></nav></header>
 <div class="calendar-grid calendar-weekdays"><?php foreach($weekdays as $weekdayName): ?><span><?= $weekdayName ?></span><?php endforeach; ?></div><div class="calendar-grid calendar-days"><?php for($i=0;$i<$gridDays;$i++):$day=$gridStart->modify('+'.$i.' days');$dateKey=$day->format('Y-m-d');$dayEvents=$byDay[$dateKey]??[];$outside=$day->format('m')!==$month->format('m');$today=$dateKey===date('Y-m-d');$selected=$dateKey===$selectedDateString;$url='?m='.$day->format('Y-m').'&date='.$dateKey.'#dia-selecionado'; ?><a class="calendar-day <?= $outside?'outside-month':'' ?> <?= $today?'is-today':'' ?> <?= $selected?'is-selected':'' ?> <?= $dayEvents?'has-events':'' ?>" href="<?= escape($url) ?>" aria-label="<?= $day->format('d/m/Y') ?>, <?= count($dayEvents) ?> sessões"><span class="calendar-day-number"><?= $day->format('j') ?></span><?php if($dayEvents): ?><span class="calendar-day-events"><?php foreach(array_slice($dayEvents,0,2) as $event): ?><span class="calendar-event-chip <?= (int)$event['concluido']?'event-done':'' ?>"><i></i><?= escape($event['titulo']) ?></span><?php endforeach; ?><?php if(count($dayEvents)>2): ?><small>+<?= count($dayEvents)-2 ?></small><?php endif; ?></span><?php endif; ?></a><?php endfor; ?></div><footer class="calendar-legend"><span><i></i> Sessão planejada</span><span><i class="legend-complete"></i> Concluída</span><span><b></b> Hoje</span></footer></section>
 <aside class="agenda-side-column"><section class="agenda-form-card"><header class="agenda-side-heading"><span class="agenda-form-icon">＋</span><div><h2>Planejar uma sessão</h2><p>Um passo de cada vez.</p></div></header><form method="POST" action="agenda.php?m=<?= $month->format('Y-m') ?>#dia-selecionado"><input type="hidden" name="csrf" value="<?= escape($_SESSION['agenda_csrf']) ?>"><input type="hidden" name="action" value="add"><label>O que vai estudar?<input name="titulo" maxlength="120" placeholder="Ex.: Revisar ligações químicas" required></label><label>Tema<input name="tema" maxlength="100" value="<?= escape($tema??'') ?>" placeholder="Ex.: Ligações químicas" required></label><div class="agenda-fields-row"><label>Data<input type="date" name="data_estudo" value="<?= escape($selectedDateString) ?>" required></label><label>Horário<input type="time" name="hora_inicio" value="16:00" required></label></div><label>Duração<select name="duracao"><option value="25">25 minutos</option><option value="30" selected>30 minutos</option><option value="45">45 minutos</option><option value="60">1 hora</option><option value="90">1h30</option></select></label><label>Observação <span class="optional-label">opcional</span><textarea name="observacoes" maxlength="500" rows="2" placeholder="Material, páginas ou lembrete"></textarea></label><button class="btn btn-primary agenda-submit" type="submit">Adicionar à agenda <span>→</span></button></form></section>
 <section class="agenda-day-card" id="dia-selecionado"><header><div><span class="panel-eyebrow">DIA SELECIONADO</span><h2><?= $selectedDate->format('d') ?> <span class="calendar-month-name"><?= escape($monthNames[(int)$selectedDate->format('n')]) ?></span></h2></div><span class="agenda-day-count"><?= count($byDay[$selectedDateString]??[]) ?></span></header><?php $selectedEvents=$byDay[$selectedDateString]??[];if($selectedEvents): ?><div class="agenda-event-list"><?php foreach($selectedEvents as $event): ?><article class="agenda-event-detail <?= (int)$event['concluido']?'is-complete':'' ?>"><div class="event-time"><?= substr($event['hora_inicio'],0,5) ?><small><?= (int)$event['duracao_minutos'] ?> min</small></div><div class="event-detail-copy"><strong><?= escape($event['titulo']) ?></strong><span><?= escape($event['tema']) ?></span><?php if($event['observacoes']): ?><small><?= escape($event['observacoes']) ?></small><?php endif; ?><em><?= (int)$event['concluido']?'Concluída':'Planejada' ?></em></div><div class="event-actions"><form method="POST" action="agenda.php?m=<?= $month->format('Y-m') ?>#dia-selecionado"><input type="hidden" name="csrf" value="<?= escape($_SESSION['agenda_csrf']) ?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="event_id" value="<?= (int)$event['id'] ?>"><input type="hidden" name="data_estudo" value="<?= escape($selectedDateString) ?>"><button type="submit" title="<?= (int)$event['concluido']?'Reabrir sessão':'Marcar como concluída' ?>" aria-label="<?= (int)$event['concluido']?'Reabrir sessão':'Marcar como concluída' ?>"><?= (int)$event['concluido']?'↶':'✓' ?></button></form><form method="POST" action="agenda.php?m=<?= $month->format('Y-m') ?>#dia-selecionado" onsubmit="return confirm('Remover esta sessão da agenda?')"><input type="hidden" name="csrf" value="<?= escape($_SESSION['agenda_csrf']) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="event_id" value="<?= (int)$event['id'] ?>"><input type="hidden" name="data_estudo" value="<?= escape($selectedDateString) ?>"><button type="submit" title="Remover sessão" aria-label="Remover sessão">×</button></form></div></article><?php endforeach; ?></div><?php else: ?><div class="agenda-day-empty"><span>◷</span><strong>Nenhuma sessão neste dia</strong><p>Use o formulário acima para reservar um tempo para estudar.</p></div><?php endif; ?></section></aside></div>
</section>
<?php require_once '../includes/footer.php'; ?>
