<?php
$titulo_pagina='Dicionário de Química'; $css_extra='study-tools.css'; require_once '../includes/header.php';
$termos=require '../includes/dictionary-data.php'; $q=trim((string)($_GET['q']??'')); $categoria=(string)($_GET['categoria']??'Todas');
$categorias=array_values(array_unique(array_column($termos,'categoria')));
$filtrados=array_filter($termos,static fn($t)=>(!$q||mb_stripos($t['termo'].' '.$t['definicao'].' '.$t['exemplo'],$q,0,'UTF-8')!==false)&&($categoria==='Todas'||$categoria===$t['categoria']));
?>
<section class="tools-hero compact-tools-hero"><span class="panel-eyebrow">CONSULTA RÁPIDA</span><h1>Dicionário de Química</h1><p>Conceitos explicados com exemplos para ajudar durante os estudos.</p></section><form class="tool-filters" method="GET"><input name="q" value="<?= escape($q) ?>" placeholder="Buscar termo ou conceito..." aria-label="Buscar no dicionário"><select name="categoria" aria-label="Filtrar por tema"><option>Todas</option><?php foreach($categorias as $cat): ?><option <?= $categoria===$cat?'selected':'' ?>><?= escape($cat) ?></option><?php endforeach; ?></select><button class="btn btn-primary">Filtrar</button><?php if($q||$categoria!=='Todas'): ?><a class="filter-reset" href="dicionario.php">Limpar</a><?php endif; ?></form><p class="explore-count"><?= count($filtrados) ?> conceito<?= count($filtrados)===1?'':'s' ?> encontrado<?= count($filtrados)===1?'':'s' ?></p>
<div class="dictionary-grid"><?php foreach($filtrados as $t): ?><article class="dictionary-card"><small><?= escape($t['categoria']) ?></small><h2><?= escape($t['termo']) ?></h2><p><?= escape($t['definicao']) ?></p><div><strong>Exemplo</strong><span><?= escape($t['exemplo']) ?></span></div></article><?php endforeach; ?><?php if(!$filtrados): ?><div class="student-empty-page"><span>Aa</span><div><h2>Não encontramos esse conceito.</h2><p>Experimente outra palavra ou limpe os filtros.</p><a class="btn btn-primary" href="dicionario.php">Ver todos os termos</a></div></div><?php endif; ?></div>
<?php require_once '../includes/footer.php'; ?>
