<?php
$titulo_pagina='Explorar'; $css_extra='study-tools.css'; require_once '../includes/header.php';
$termos=require '../includes/dictionary-data.php'; $formulas=require '../includes/formula-data.php'; $q=trim((string)($_GET['q']??'')); $tipo=(string)($_GET['tipo']??'todos');
$materiais=$simulados=$questoes=[];
if($q!==''&&in_array($tipo,['todos','conteudos'],true)){$s=$pdo->prepare('SELECT id,titulo,resumo,categoria FROM conteudos WHERE titulo LIKE :q1 OR resumo LIKE :q2 OR categoria LIKE :q3 ORDER BY titulo');$like='%'.$q.'%';$s->execute(['q1'=>$like,'q2'=>$like,'q3'=>$like]);$materiais=$s->fetchAll();}
if($q!==''&&in_array($tipo,['todos','simulados'],true)){$s=$pdo->prepare('SELECT id,titulo,descricao FROM simulados WHERE titulo LIKE :q1 OR descricao LIKE :q2 ORDER BY titulo');$like='%'.$q.'%';$s->execute(['q1'=>$like,'q2'=>$like]);$simulados=$s->fetchAll();}
if($q!==''&&in_array($tipo,['todos','questoes'],true)){$s=$pdo->prepare('SELECT q.id,q.enunciado,c.id AS conteudo_id,c.titulo AS conteudo_titulo FROM questoes q LEFT JOIN conteudos c ON c.id=q.conteudo_id WHERE q.enunciado LIKE :q1 OR q.explicacao LIKE :q2 ORDER BY q.id DESC LIMIT 30');$like='%'.$q.'%';$s->execute(['q1'=>$like,'q2'=>$like]);$questoes=$s->fetchAll();}
$matches=static fn($text)=>$q!==''&&mb_stripos($text,$q,0,'UTF-8')!==false;
$termosEncontrados=in_array($tipo,['todos','dicionario'],true)?array_filter($termos,fn($t)=>$matches($t['termo'].' '.$t['categoria'].' '.$t['definicao'])):[];
$formulasEncontradas=in_array($tipo,['todos','formulas'],true)?array_filter($formulas,fn($f)=>$matches($f['nome'].' '.$f['tema'].' '.$f['formula'].' '.$f['descricao'])):[];
$total=count($materiais)+count($simulados)+count($questoes)+count($termosEncontrados)+count($formulasEncontradas);
?>
<section class="tools-hero"><span class="panel-eyebrow">BUSCA DA PLATAFORMA</span><h1>O que você quer estudar?</h1><p>Encontre conteúdos, simulados, questões, conceitos e fórmulas em um só lugar.</p><form class="explore-search" method="GET"><label class="sr-only" for="explore-q">Buscar assunto</label><input id="explore-q" name="q" value="<?= escape($q) ?>" placeholder="Ex.: ligações, pH, concentração..." required><select name="tipo" aria-label="Filtrar tipo"><option value="todos" <?= $tipo==='todos'?'selected':'' ?>>Tudo</option><option value="conteudos" <?= $tipo==='conteudos'?'selected':'' ?>>Conteúdos</option><option value="simulados" <?= $tipo==='simulados'?'selected':'' ?>>Simulados</option><option value="questoes" <?= $tipo==='questoes'?'selected':'' ?>>Questões</option><option value="dicionario" <?= $tipo==='dicionario'?'selected':'' ?>>Dicionário</option><option value="formulas" <?= $tipo==='formulas'?'selected':'' ?>>Fórmulas</option></select><button class="btn btn-primary">Buscar <span>⌕</span></button></form></section>
<?php if($q===''): ?><section class="explore-shortcuts"><a href="trilha.php"><span>◎</span><strong>Minha trilha</strong><small>Monte seu plano de estudos</small></a><a href="dicionario.php"><span>Aa</span><strong>Dicionário</strong><small>Conceitos da química</small></a><a href="formulas.php"><span>ƒ</span><strong>Fórmulas</strong><small>Relações e unidades</small></a><a href="chat.php"><span>✦</span><strong>Ajuda nos estudos</strong><small>Converse sobre suas dúvidas</small></a><a href="conteudos.php"><span>▤</span><strong>Conteúdos</strong><small>Materiais publicados</small></a></section>
<?php else: ?><p class="explore-count"><?= $total ?> resultado<?= $total===1?'':'s' ?> para <strong>“<?= escape($q) ?>”</strong></p><div class="explore-results">
<?php foreach($materiais as $item): ?><a class="explore-result" href="conteudo.php?id=<?= (int)$item['id'] ?>"><small>CONTEÚDO · <?= escape($item['categoria']) ?></small><strong><?= escape($item['titulo']) ?></strong><span><?= escape($item['resumo']) ?></span><b>Estudar →</b></a><?php endforeach; ?>
<?php foreach($simulados as $item): ?><a class="explore-result" href="simulado.php?id=<?= (int)$item['id'] ?>"><small>SIMULADO</small><strong><?= escape($item['titulo']) ?></strong><span><?= escape($item['descricao']??'') ?></span><b>Praticar →</b></a><?php endforeach; ?>
<?php foreach($questoes as $item): ?><a class="explore-result" href="quiz.php<?= $item['conteudo_id']?'?conteudo='.(int)$item['conteudo_id']:'' ?>"><small>QUESTÃO · <?= escape($item['conteudo_titulo']??'Química geral') ?></small><strong><?= escape($item['enunciado']) ?></strong><b>Praticar questões relacionadas →</b></a><?php endforeach; ?>
<?php foreach($termosEncontrados as $item): ?><article class="explore-result"><small>DICIONÁRIO · <?= escape($item['categoria']) ?></small><strong><?= escape($item['termo']) ?></strong><span><?= escape($item['definicao']) ?></span><b>Exemplo: <?= escape($item['exemplo']) ?></b></article><?php endforeach; ?>
<?php foreach($formulasEncontradas as $item): ?><article class="explore-result"><small>FÓRMULA · <?= escape($item['tema']) ?></small><strong><?= escape($item['nome']) ?> <em><?= escape($item['formula']) ?></em></strong><span><?= escape($item['descricao']) ?></span><b><?= escape($item['unidade']) ?></b></article><?php endforeach; ?>
<?php if(!$total): ?><div class="student-empty-page"><span>⌕</span><div><h2>Nenhum resultado encontrado.</h2><p>Tente outro termo ou selecione “Tudo” para ampliar a busca.</p><a href="explorar.php" class="btn btn-primary">Limpar busca</a></div></div><?php endif; ?></div><?php endif; ?>
<?php require_once '../includes/footer.php'; ?>

