<?php
$titulo_pagina='Minha trilha de aprendizagem'; $css_extra='study-tools.css'; $script_extra='study-path.js'; require_once '../includes/header.php';
$tema=trim((string)($_GET['preciso']??'')); $ja_sei=trim((string)($_GET['ja_sei']??'')); $nivel=(string)($_GET['nivel']??'iniciando');
$nivel=in_array($nivel,['iniciando','revisando','aprofundando'],true)?$nivel:'iniciando';
$categorias=$pdo->query('SELECT DISTINCT categoria FROM conteudos ORDER BY categoria')->fetchAll(PDO::FETCH_COLUMN);
$conteudos=$simulados=[]; $termosEncontrados=$formulasEncontradas=[]; $questoesPorConteudo=[];
if($tema!==''){
 $like='%'.$tema.'%';
 $stmt=$pdo->prepare('SELECT id,titulo,resumo,categoria FROM conteudos WHERE titulo LIKE :q1 OR resumo LIKE :q2 OR categoria LIKE :q3 ORDER BY titulo LIMIT 8');$stmt->execute(['q1'=>$like,'q2'=>$like,'q3'=>$like]);$conteudos=$stmt->fetchAll();
 $termos=require '../includes/dictionary-data.php';$formulas=require '../includes/formula-data.php';
 $contains=static fn($text)=>mb_stripos($text,$tema,0,'UTF-8')!==false;
 $termosEncontrados=array_slice(array_values(array_filter($termos,fn($t)=>$contains($t['termo'].' '.$t['categoria'].' '.$t['definicao']))),0,4);
 $formulasEncontradas=array_slice(array_values(array_filter($formulas,fn($f)=>$contains($f['nome'].' '.$f['tema'].' '.$f['descricao']))),0,4);
 if($conteudos){$ids=array_map(static fn($item)=>(int)$item['id'],$conteudos);$marks=implode(',',array_fill(0,count($ids),'?'));$stmt=$pdo->prepare("SELECT conteudo_id,COUNT(*) AS total FROM questoes WHERE conteudo_id IN ($marks) AND tipo='multipla' GROUP BY conteudo_id");$stmt->execute($ids);foreach($stmt->fetchAll() as $row)$questoesPorConteudo[(int)$row['conteudo_id']]=(int)$row['total'];$stmt=$pdo->prepare("SELECT id,titulo,descricao,conteudo_id FROM simulados WHERE conteudo_id IN ($marks) ORDER BY id DESC");$stmt->execute($ids);$simulados=$stmt->fetchAll();}
}
$searchUrl='explorar.php?q='.rawurlencode($tema);$chatUrl='chat.php?tema='.rawurlencode($tema);
?>
<section class="tools-hero path-hero"><span class="panel-eyebrow">PLANO DE ESTUDO PERSONALIZADO</span><h1>Seu próximo passo começa pelo que você quer aprender.</h1><p>Conte o que já sabe e onde quer chegar. A plataforma reúne materiais e atividades para você escolher como estudar.</p></section>
<form class="path-form" method="GET"><div class="path-form-heading"><span>01</span><div><strong>Defina seu foco</strong><small>Você pode escrever um tema da aula ou uma dúvida específica.</small></div></div><div class="path-fields"><label>Já entendo um pouco de <input name="ja_sei" value="<?= escape($ja_sei) ?>" placeholder="Ex.: átomos e tabela periódica"></label><label><span>Quero aprender <b>*</b></span><input name="preciso" value="<?= escape($tema) ?>" placeholder="Ex.: ligações químicas, pH, mol..." required></label><label>Como quer estudar?<select name="nivel"><option value="iniciando" <?= $nivel==='iniciando'?'selected':'' ?>>Estou começando</option><option value="revisando" <?= $nivel==='revisando'?'selected':'' ?>>Quero revisar e praticar</option><option value="aprofundando" <?= $nivel==='aprofundando'?'selected':'' ?>>Quero me desafiar</option></select></label></div><div class="topic-chips"><span>Ideias para começar:</span><?php foreach(array_slice(array_unique(array_merge(['Estrutura atômica','Ligações químicas','Ácidos e bases','Soluções','Estequiometria','Tabela periódica'],$categorias)),0,8) as $chip): ?><button type="button" data-topic="<?= escape($chip) ?>"><?= escape($chip) ?></button><?php endforeach; ?></div><button class="btn btn-primary path-submit" type="submit">Montar meu caminho <span>→</span></button></form>
<?php if($tema!==''): ?><section class="path-results"><header class="path-results-heading"><div><span class="panel-eyebrow">SEU PLANO PARA</span><h2><?= escape($tema) ?></h2><?php if($ja_sei): ?><p>Partindo do que você já conhece: <strong><?= escape($ja_sei) ?></strong></p><?php endif; ?></div><span class="path-level"><?= $nivel==='iniciando'?'COMEÇANDO':($nivel==='revisando'?'REVISÃO E PRÁTICA':'DESAFIO') ?></span></header>
<div class="path-option-grid">
<?php if($conteudos): foreach($conteudos as $item): ?><article class="path-option path-option-featured"><span class="path-option-icon">▤</span><small>LEITURA · <?= escape($item['categoria']) ?></small><h3><?= escape($item['titulo']) ?></h3><p><?= escape($item['resumo']) ?></p><a href="conteudo.php?id=<?= (int)$item['id'] ?>">Ler conteúdo <b>→</b></a></article><?php endforeach; endif; ?>
<?php if($termosEncontrados): foreach($termosEncontrados as $item): ?><article class="path-option"><span class="path-option-icon pink">Aa</span><small>DICIONÁRIO · <?= escape($item['categoria']) ?></small><h3><?= escape($item['termo']) ?></h3><p><?= escape($item['definicao']) ?></p><a href="dicionario.php?q=<?= rawurlencode($item['termo']) ?>">Revisar conceito <b>→</b></a></article><?php endforeach; endif; ?>
<?php if($formulasEncontradas): foreach($formulasEncontradas as $item): ?><article class="path-option"><span class="path-option-icon">ƒ</span><small>FÓRMULA · <?= escape($item['tema']) ?></small><h3><?= escape($item['nome']) ?></h3><div class="path-formula"><?= escape($item['formula']) ?></div><p><?= escape($item['unidade']) ?></p><a href="formulas.php?q=<?= rawurlencode($item['nome']) ?>">Ver fórmula <b>→</b></a></article><?php endforeach; endif; ?>
<?php foreach($conteudos as $item): if(($questoesPorConteudo[(int)$item['id']]??0)>0): ?><article class="path-option"><span class="path-option-icon pink">✎</span><small>PRÁTICA · <?= (int)$questoesPorConteudo[(int)$item['id']] ?> QUESTÕES</small><h3>Teste o que aprendeu</h3><p>Responda questões de <?= escape($item['titulo']) ?> e receba feedback.</p><a href="quiz.php?conteudo=<?= (int)$item['id'] ?>">Começar quiz <b>→</b></a></article><?php endif; endforeach; ?>
<?php foreach($simulados as $item): ?><article class="path-option"><span class="path-option-icon pink">⚡</span><small>DESAFIO</small><h3><?= escape($item['titulo']) ?></h3><p><?= escape($item['descricao']??'Pratique esse assunto em um simulado.') ?></p><a href="simulado.php?id=<?= (int)$item['id'] ?>">Fazer simulado <b>→</b></a></article><?php endforeach; ?>
<article class="path-option"><span class="path-option-icon pink">✦</span><small>APOIO PERSONALIZADO</small><h3>Converse sobre esse tema</h3><p>Peça uma explicação, um exemplo ou ajuda para entender por onde começar.</p><a href="<?= escape($chatUrl) ?>">Perguntar no chat <b>→</b></a></article>
<article class="path-option"><span class="path-option-icon">⌕</span><small>OUTRAS OPÇÕES</small><h3>Explore mais recursos</h3><p>Busque questões, materiais, conceitos e fórmulas relacionados a “<?= escape($tema) ?>”.</p><a href="<?= escape($searchUrl) ?>">Ver resultados <b>→</b></a></article>
<?php if(!$conteudos&&!$termosEncontrados&&!$formulasEncontradas&&!$simulados): ?><div class="path-no-match"><strong>Ainda não há um material publicado exatamente com esse tema.</strong><span>Mesmo assim, você pode perguntar no chat, buscar por palavras relacionadas ou explorar os flashcards.</span><div><a href="<?= escape($chatUrl) ?>">Pedir uma explicação →</a><a href="flashcards.php">Revisar flashcards →</a><a href="<?= escape($searchUrl) ?>">Buscar na plataforma →</a></div></div><?php endif; ?></div></section><?php else: ?><section class="path-empty-prompt"><span>✧</span><div><strong>Seu plano aparece aqui.</strong><p>Escreva um assunto acima para receber opções de leitura, revisão, exercícios e ajuda.</p></div></section><?php endif; ?>
<?php require_once '../includes/footer.php'; ?>



