(() => {
 const form=document.getElementById('chat-form'), input=document.getElementById('chat-input'), messages=document.getElementById('chat-messages');
 if(!form||!input||!messages)return;
 const rules=[
  [/\b(mol|avogadro|6[,.]?022)\b/i,'O mol é a unidade de quantidade de matéria. Um mol contém aproximadamente 6,022 × 10²³ entidades (átomos, moléculas ou íons). Para converter massa em mol, use <strong>n = m / M</strong>: divida a massa pela massa molar.'],
  [/\b(concentra|molaridade|mol\/l|mol\/l|solu[cç][aã]o)\b/i,'A concentração molar relaciona a quantidade de soluto ao volume total da solução: <strong>C = n / V</strong>, em mol/L. Se você tem a massa, primeiro calcule n = m/M. Lembre-se de converter o volume para litros.'],
  [/\b(ph|acidez|[aá]cido|base|hidroxila)\b/i,'O pH indica a acidez de uma solução. Em condições usuais, pH menor que 7 é ácido, 7 é neutro e maior que 7 é básico. Para calcular a partir de [H⁺], usamos <strong>pH = −log[H⁺]</strong>. Cada unidade de pH representa uma variação de dez vezes na concentração de H⁺.'],
  [/\b(liga[cç][aã]o|i[oô]nica|covalente|met[aá]lica)\b/i,'Na ligação <strong>iônica</strong>, há transferência de elétrons e atração entre íons; costuma ocorrer entre metal e ametal. Na <strong>covalente</strong>, ametais compartilham pares de elétrons. Na <strong>metálica</strong>, cátions metálicos ficam unidos por elétrons deslocalizados.'],
  [/\b(estequiometr|balance|reagente|produto|propor[cç][aã]o)\b/i,'Na estequiometria, comece balanceando a equação. Os coeficientes mostram a proporção em mol entre reagentes e produtos. Depois converta o dado para mol (n = m/M), use a proporção dos coeficientes e converta para a unidade pedida.'],
  [/\b(massa molar|massa at[oô]mica|g\/mol)\b/i,'A massa molar (M) é a massa de 1 mol de uma substância, em g/mol. Para um composto, some as massas atômicas de cada elemento multiplicadas pela quantidade de átomos indicada na fórmula. Depois use n = m/M para achar os mols.'],
  [/\b(densidade)\b/i,'A densidade relaciona massa e volume: <strong>d = m / V</strong>. Confira se as unidades são compatíveis, como g/mL ou g/cm³. Para encontrar outra variável, reorganize a expressão: m = d·V ou V = m/d.'],
  [/\b(dilui[cç][aã]o|diluir)\b/i,'Na diluição, adicionamos solvente e a quantidade de soluto permanece a mesma. Use <strong>C₁V₁ = C₂V₂</strong>. Os volumes devem estar na mesma unidade e as concentrações na mesma unidade.'],
  [/\b(g[aá]s|clapeyron|press[aã]o|volume)\b/i,'Para um gás ideal, a equação é <strong>P·V = n·R·T</strong>. Use temperatura em kelvin (K = °C + 273,15) e escolha R compatível com as unidades de pressão e volume.'],
  [/\b(oxida[cç][aã]o|redu[cç][aã]o|redox|el[eé]tron)\b/i,'Em uma reação de oxirredução, <strong>oxidação é perda de elétrons</strong> e aumento do número de oxidação; <strong>redução é ganho de elétrons</strong> e diminuição do número de oxidação. Uma dica: “perde oxida, ganha reduz”.'],
  [/\b(temperatura|calor|termoqu[ií]mica|calor sens[ií]vel)\b/i,'Para o calor sensível (sem mudança de estado), use <strong>Q = m·c·ΔT</strong>. ΔT = Tfinal − Tinicial. Verifique as unidades de massa e calor específico. Se a questão tratar de reação química, ela pode pedir entalpia (ΔH) em vez disso.'],
  [/\b(estrutura at[oô]mica|n[uú]mero at[oô]mico|pr[oó]ton|n[eê]utron|el[eé]tron)\b/i,'O número atômico <strong>Z é o número de prótons</strong> e identifica o elemento. O número de massa é <strong>A = Z + N</strong> (prótons + nêutrons). Em um átomo neutro, prótons = elétrons; em íons, a diferença determina a carga.']
 ];
 function add(text,kind){const article=document.createElement('article');article.className='chat-message '+(kind==='user'?'user-message':'assistant-message');const avatar=document.createElement('span');avatar.className='message-avatar';avatar.textContent=kind==='user'?'Você':'✦';const body=document.createElement('div');const label=document.createElement('small');label.textContent=kind==='user'?'VOCÊ':'ASSISTENTE';const p=document.createElement('p');if(kind==='assistant')p.innerHTML=text;else p.textContent=text;body.append(label,p);article.append(avatar,body);messages.append(article);messages.scrollTop=messages.scrollHeight;window.qsRefreshLanguage?.();}
 function answer(q){const rule=rules.find(([pattern])=>pattern.test(q));return rule?rule[1]:'Ainda não tenho uma explicação específica para essa pergunta. Tente incluir o tema (como mol, pH, ligações ou estequiometria), consulte o <a href="dicionario.php">dicionário</a> e as <a href="formulas.php">fórmulas</a>, ou peça ajuda ao professor.';}
 function send(q){q=q.trim();if(!q)return;add(q,'user');input.value='';window.setTimeout(()=>add(answer(q),'assistant'),250);}
 form.addEventListener('submit',e=>{e.preventDefault();send(input.value)});
 document.querySelectorAll('.chat-suggestions button').forEach(button=>button.addEventListener('click',()=>send(button.textContent)));
 input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit()}});
 const topic=document.querySelector('.study-chat')?.dataset.topic; if(topic){input.placeholder='Escreva sua dúvida sobre '+topic+'...';const safe=document.createElement('span');safe.textContent=topic;add('Vamos focar em <strong>'+safe.innerHTML+'</strong>. O que você gostaria de entender melhor?','assistant');}
})();
